### PR TITLE
Added feature to allow users to customize their terminal and ssh comm…

### PR DESCRIPTION
**Pull request by rsmith-integrate**
We use a variety of different terminals so we quickly added the ability to change the Terminal start command as well as the SSH command.

### CODE REVIEW

**Comment by MekDrop** [comment]
@rsmith-integrate, I have proposed similar changes but different implementation as #17 on this August however no ping back from owners. There was also another guy who have tried to add other changes and also there was no ping. That's why I believe this project is died ;(

**Comment by amitailanciano** [comment]
This project is currently no longer under active development, but we might pick it back up again in the future.. feel free to fork it and make it better!

**Comment by nrogers64** [comment]
@amitailanciano I would suggest updating http://vagrantmanager.com/windows/ and also the README in this repository to indicate that this project isn't under active development. Your README currently encourages code contributions.

**Comment by MekDrop** [comment]
I agree with @nrogers64. I'ts a bit annoying when you are make a contribution and there are no feedback and then you are waiting about 6 months for anything from the author/owner.

Last week I have decided to start a remake of this project. To make it from the start be able to run on any mono/.net supported architecture (Win, MacOsX, Linux). I'm not sure how good for me will everything going (I don't have much time for it)  but at least from what I have read I think this task is possible. It's called [Guiva](https://github.com/guiva/guiva) and right now it's at very early stages - almost nothing there works as should be.

**Pull request closed without merging**
